name: Run Test Cases

on:
  push:
    branches:
      - main
    # This will trigger the workflow only if the following files are changed
    paths:
      - "lib/**"
      - "test/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "package.json"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:coverage
